### ISSUE TITLE
requirements.txt文件内包版本有冲突

### ISSUE THREAD

**Issue by xxWeiDG** [MooreThreads/TurboRAG#1]
1.python3.10和llama-index==0.11.22有冲突，会导致TypeError:Plain typing.TypeAlias is not valid as type argument需要python版本降低
2.安装transformers==4.40.2后，sentenc-transformers 3.2.1 无法安装，需要升级transformers>=4.41.0

**Comment by fangtaosong** [comment]
如何解决的呢

**Comment by xxWeiDG** [comment]
> 如何解决的呢

按照推荐python版本安装就好了
